src/Entity/Etats.php
<?php

namespace App\Entity;

use App\Repository\EtatsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EtatsRepository::class)
 */
class Etats
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lib_etat;

    /**
     * @ORM\OneToMany(targetEntity=Menus::class, mappedBy="etats")
     */
    private $menus;

    /**
     * @ORM\OneToMany(targetEntity=Categories::class, mappedBy="etats")
     */
    private $category;

    /**
     * @ORM\OneToMany(targetEntity=Pages::class, mappedBy="etats")
     */
    private $pages;

    /**
     * @ORM\OneToMany(targetEntity=Commentaires::class, mappedBy="etats")
     */
    private $commentaire;

    /**
     * @ORM\OneToMany(targetEntity=MetaPage::class, mappedBy="etats")
     */
    private $metapage;

    public function __construct()
    {
        $this->menus = new ArrayCollection();
        $this->category = new ArrayCollection();
        $this->pages = new ArrayCollection();
        $this->commentaire = new ArrayCollection();
        $this->metapage = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibEtat(): ?string
    {
        return $this->lib_etat;
    }

    public function setLibEtat(string $lib_etat): self
    {
        $this->lib_etat = $lib_etat;

        return $this;
    }

    /**
     * @return Collection|Menus[]
     */
    public function getMenus(): Collection
    {
        return $this->menus;
    }

    public function addMenu(Menus $menu): self
    {
        if (!$this->menus->contains($menu)) {
            $this->menus[] = $menu;
            $menu->setEtats($this);
        }

        return $this;
    }

    public function removeMenu(Menus $menu): self
    {
        if ($this->menus->contains($menu)) {
            $this->menus->removeElement($menu);
            // set the owning side to null (unless already changed)
            if ($menu->getEtats() === $this) {
                $menu->setEtats(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Categories[]
     */
    public function getCategory(): Collection
    {
        return $this->category;
    }

    public function addCategory(Categories $category): self
    {
        if (!$this->category->contains($category)) {
            $this->category[] = $category;
            $category->setEtats($this);
        }

        return $this;
    }

    public function removeCategory(Categories $category): self
    {
        if ($this->category->contains($category)) {
            $this->category->removeElement($category);
            // set the owning side to null (unless already changed)
            if ($category->getEtats() === $this) {
                $category->setEtats(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Pages[]
     */
    public function getPages(): Collection
    {
        return $this->pages;
    }

    public function addPage(Pages $page): self
    {
        if (!$this->pages->contains($page)) {
            $this->pages[] = $page;
            $page->setEtats($this);
        }

        return $this;
    }

    public function removePage(Pages $page): self
    {
        if ($this->pages->contains($page)) {
            $this->pages->removeElement($page);
            // set the owning side to null (unless already changed)
            if ($page->getEtats() === $this) {
                $page->setEtats(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Commentaires[]
     */
    public function getCommentaire(): Collection
    {
        return $this->commentaire;
    }

    public function addCommentaire(Commentaires $commentaire): self
    {
        if (!$this->commentaire->contains($commentaire)) {
            $this->commentaire[] = $commentaire;
            $commentaire->setEtats($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaires $commentaire): self
    {
        if ($this->commentaire->contains($commentaire)) {
            $this->commentaire->removeElement($commentaire);
            // set the owning side to null (unless already changed)
            if ($commentaire->getEtats() === $this) {
                $commentaire->setEtats(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|MetaPage[]
     */
    public function getMetapage(): Collection
    {
        return $this->metapage;
    }

    public function addMetapage(MetaPage $metapage): self
    {
        if (!$this->metapage->contains($metapage)) {
            $this->metapage[] = $metapage;
            $metapage->setEtats($this);
        }

        return $this;
    }

    public function removeMetapage(MetaPage $metapage): self
    {
        if ($this->metapage->contains($metapage)) {
            $this->metapage->removeElement($metapage);
            // set the owning side to null (unless already changed)
            if ($metapage->getEtats() === $this) {
                $metapage->setEtats(null);
            }
        }

        return $this;
    }

        /**
     * Transform to string
     * 
     * @return string
     */
    public function __toString()
    {
        return (string) $this->getLibEtat();
    }
}

src/Form/EtatsType.php
<?php

namespace App\Form;

use App\Entity\Etats;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EtatsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('lib_etat')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Etats::class,
        ]);
    }
}

src/Controller/EtatsController.php
<?php

namespace App\Controller;

use App\Entity\Etats;
use App\Form\EtatsType;
use App\Repository\EtatsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/etats")
 */
class EtatsController extends AbstractController
{
    /**
     * @Route("/", name="etats_index", methods={"GET"})
     */
    public function index(EtatsRepository $etatsRepository): Response
    {
        return $this->render('etats/index.html.twig', [
            'etats' => $etatsRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="etats_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $etat = new Etats();
        $form = $this->createForm(EtatsType::class, $etat);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($etat);
            $entityManager->flush();

            return $this->redirectToRoute('etats_index');
        }

        return $this->render('etats/new.html.twig', [
            'etat' => $etat,
            'form' => $form->createView(),
        ]);
    }

    

    /**
     * @Route("/{id}/edit", name="etats_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Etats $etat): Response
    {
        $form = $this->createForm(EtatsType::class, $etat);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('etats_index');
        }

        return $this->render('etats/edit.html.twig', [
            'etat' => $etat,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="etats_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Etats $etat): Response
    {
        if ($this->isCsrfTokenValid('delete'.$etat->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($etat);
            $entityManager->flush();
        }

        return $this->redirectToRoute('etats_index');
    }

 /**
     * @Route("/etats/delete/{id}", name="delete_etats")
     */
    public function supprimer(Etats $etat)
    {
        if ($etat)
        {
            $em = $this->getDoctrine()->getManager();
            $em->remove($etat); //pour supprimer l'objet article
            $em->flush(); //commit transaction
            //j'affiche le message en cas de succès
            $this->get('session')->getFlashBag()->add('message', 'Suppression effectuée avec succès');
            //redirection vers la liste des articles
            return $this->redirectToRoute('etats_index');

        }
       throw new NotFoundHttpException();
       
    }

}

templates/etats/_delete_form.html.twig
<form method="post" action="{{ path('etats_delete', {'id': etat.id}) }}" onsubmit="return confirm('Etes-vous sûr de vouloir supprimer cette ligne ?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ etat.id) }}">
    <button class="btn btn-warning">Supprimer</button>
</form>

templates/etats/_form.html.twig
{{ form_start(form) }}
 <div class="form-horizontal">
    {{ form_row(form.lib_etat, {'label':false, 'attr':{'class':'form-control', 'placeholder':'Libellé...'}}) }}
     <div class="form-group float-left"><button class="btn btn-success">{{ button_label|default('Ajouter') }}</button></div>
     <div class="form-group float-right"> <a class="btn btn-danger" href="{{ path('etats_index') }}">Fermer</a></div>
    <br>
   
</div>   
{{ form_end(form) }}

templates/etats/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Etats{% endblock %}

{% block body %}
<div class="container">
    <h1>Edition Etats</h1>

   

     <div class="row">
            <div class="col-md-12">
                {{ include('etats/_form.html.twig', {'button_label': 'Mettre à jour'}) }}
            </div>
        </div>

</div>
    {# {{ include('etats/_delete_form.html.twig') }} #}
{% endblock %}

templates/etats/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Admin : Etats{% endblock %}

{% block body %}
<style>
   
    .negatif {background-color:red;}
    .positif {background-color:green;}
    .fond-pair {background-color:#f5f5f5;}
    .fond-impair {background-color:#c0c0c0;}
</style>
<div class="container-fluid">
    <h1>Gestion etats</h1>
<div class="float-right" ><a href="{{ path('etats_new')}}" class="btn btn-sm btn-primary" />Créer</a></div>
    <br/>
    <br/>
  <table class="table table-bordered" id="tbl-etat">
        <thead class="thead-dark">
            <tr>
                <th>#</th>
                <th>Libellé</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for etat in etats %}
            <tr>
                {# <td>{{ etat.id }}</td> #}
                <th scope="row">{{ loop.index  }}</th>
                <td>{{ etat.libEtat }}</td>
                <td>
                    {# <a href="{{ path('etats_show', {'id': etat.id}) }}">show</a> #}
                    <a href="{{ path('etats_edit', {'id': etat.id}) }}">Editer</a>
                    <a href="{{ path('delete_etats', {'id': etat.id}) }}" onclick="return confirm('Etes-vous sûre de vouloir supprimer cette ligne ?')">Supprimer</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">Aucune donnée trouvée</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    </div>
    {# {{ include('etats/_delete_form.html.twig') }} #}
{% endblock %}

templates/etats/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajout etat{% endblock %}
{# this tag only applies to the forms defined in this template #}
{% form_theme form 'bootstrap_4_layout.html.twig' %}
{% block body %}
    <div class="container">
    <h2>Création etat</h2>
  <!-- Page Content -->

        <div class="row">
            <div class="col-md-12">
                 {{ include('etats/_form.html.twig') }}
            </div>
        </div>
    </div>
{% endblock %}

templates/etats/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Etats{% endblock %}

{% block body %}
    <h1>Etats</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ etat.id }}</td>
            </tr>
            <tr>
                <th>Lib_etat</th>
                <td>{{ etat.libEtat }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('etats_index') }}">back to list</a>

    <a href="{{ path('etats_edit', {'id': etat.id}) }}">edit</a>

    {{ include('etats/_delete_form.html.twig') }}
{% endblock %}